env: 
  es6: true
  node: true
  browser: true

extends:
  - plugin:vue/essential
  - eslint:recommended

parserOptions: 
  ecmaVersion: 2018

globals:
  d3: true
  app: true
  Vue: true
  config: true
  echarts: true

rules: 
  arrow-parens:
    - warn
    - as-needed
  arrow-spacing: warn
  block-spacing: warn
  brace-style: warn
  comma-dangle:
    - warn
    - always-multiline
  comma-spacing: warn
  computed-property-spacing: warn
  dot-location:
    - warn
    - property
  eqeqeq:
    - warn
    - always
  func-call-spacing: warn
  generator-star-spacing:
    - warn
    - before: false
      after: true
  indent:
    - warn
    - 2
    - SwitchCase: 1
  key-spacing: warn
  keyword-spacing: warn
  no-console: off
  no-var: error
  no-unused-vars: warn
  object-curly-spacing:
    - warn
    - always
  quotes:
    - warn
    - single
  rest-spread-spacing: warn
  semi:
    - error
    - never
  semi-spacing: warn
  space-before-function-paren:
    - warn
    - never
  switch-colon-spacing: warn
  yield-star-spacing:
    - warn
    - before: false
      after: true
